# Generated by Django 3.2 on 2021-06-07 22:42

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_kpi"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceIndicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                ("amount_of_surveys", models.IntegerField()),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="date"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="operations.store",
                    ),
                ),
            ],
        ),
    ]
