# Generated by Django 3.2 on 2021-06-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_auto_20210614_2335"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="store",
        ),
        migrations.AddField(
            model_name="product",
            name="stores",
            field=models.ManyToManyField(
                related_name="products", to="operations.Store"
            ),
        ),
    ]
