# Generated by Django 3.2 on 2021-07-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_auto_20210615_0317"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpi",
            name="name",
        ),
        migrations.RemoveField(
            model_name="kpi",
            name="units",
        ),
        migrations.RemoveField(
            model_name="kpi",
            name="value",
        ),
        migrations.AddField(
            model_name="kpi",
            name="contribution",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpi",
            name="gross_sale",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpi",
            name="net_sale",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kpi",
            name="transactions",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
