# Generated by Django 3.2 on 2021-07-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_auto_20210705_0407"),
        ("operations", "0009_auto_20210706_0332"),
    ]

    operations = []
