# Generated by Django 3.2 on 2021-07-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_merge_0009_auto_20210705_0407_0009_auto_20210706_0332"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
