name: staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to ECR registry
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 556359875842.dkr.ecr.us-east-2.amazonaws.com

      - name: Build application image
        run: docker build --file Dockerfile --tag 556359875842.dkr.ecr.us-east-2.amazonaws.com/backend:staging .

      - name: Push application image
        run: docker push 556359875842.dkr.ecr.us-east-2.amazonaws.com/backend:staging

      - name: Register task definition
        run: aws ecs register-task-definition --cli-input-json file://aws/staging/task.json

      - name: Execute migrations using a standalone task
        run: aws ecs run-task --cluster staging --task-definition application-staging --overrides file://aws/staging/migration-override.json --enable-execute-command --count 1

      - name: Update application service
        run: aws ecs update-service --cluster staging --service application-staging --task-definition application-staging --force-new-deployment
